/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      300,                                       
            catalogName:    "ti.catalog.c6000",
            deviceName:     "TMS320C6748",
            customMemoryMap:
           [          
                ["IROM", 
                     {
                        name: "IROM",
                        base: 0x11700000,                    
                        len: 0x00100000,                    
                        space: "code/data",
                        access: "RX",
                     }
                ],
                ["IRAM", 
                     {
                        name: "IRAM",
                        base: 0x11800000,                    
                        len: 0x00040000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["L3_CBA_RAM", 
                     {
                        name: "L3_CBA_RAM",
                        base: 0x80000000,                    
                        len: 0x00020000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["APP_CODE_MEM", 
                     {
                        name: "APP_CODE_MEM",
                        base: 0xC0000000,                    
                        len: 0x1e00000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["APP_CACHED_DATA_MEM", 
                     {
                        name: "APP_CACHED_DATA_MEM",
                        base: 0xc1f01000,                    
                        len: 0x1400000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["APP_UNCACHED_DATA_BLK3_MEM", 
                     {
                        name: "APP_UNCACHED_DATA_BLK3_MEM",
                        base: 0xc3301000,                    
                        len: 0x1400000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["APP_CACHED_DATA_BLK1_MEM", 
                     {
                        name: "APP_CACHED_DATA_BLK1_MEM",
                        base: 0xc4701000,                    
                        len: 0xa00000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["APP_CACHED_DATA_BLK2_MEM", 
                     {
                        name: "APP_CACHED_DATA_BLK2_MEM",
                        base: 0xc5101000,                    
                        len: 0xa00000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["APP_CACHED_BIOS_RSVD_MEM", 
                     {
                        name: "APP_CACHED_BIOS_RSVD_MEM",
                        base: 0xc5b01000,                    
                        len: 0x1000000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
                ["DDR_CFG", 
                     {
                        name: "DDR_CFG",
                        base: 0xc6b01000,                    
                        len: 0xa00000,                    
                        space: "code/data",
                        access: "RWX",
                     }
                ],
           ],
          l1DMode: "32k",
          l1PMode: "32k",
          l2Mode: "0k",

    });
    
instance :
    
    override config string codeMemory  = "APP_CODE_MEM";   
    override config string dataMemory  = "APP_CACHED_DATA_MEM";                                
    override config string stackMemory = "APP_CACHED_DATA_MEM";

    config String l1DMode = "32k";
    config String l1PMode = "32k";
    config String l2Mode = "0k";
}
